name: notes_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.9.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  modal_progress_hud_nsn: ^0.5.1
  intl: ^0.20.2
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf

# إعدادات أيقونة اللانشر
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/logo.png
  adaptive_icon_foreground: assets/icon/logo.png
  adaptive_icon_background: "#121212"


# إعدادات السبلاتش
flutter_native_splash:
  image: assets/icon/logo.png
  color: "#121212"

  android_12:
    color: "#121212"
    image: assets/icon/logo.png

  android: true
  ios: true
